### ISSUE TITLE
Add Version number

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-m3aawg#40]
Footer:
<img width="1270" alt="Screen Shot 2020-05-02 at 2 36 30 AM" src="https://user-images.githubusercontent.com/11865/80831622-bcefe500-8c1d-11ea-97da-475cdcf97f4d.png">

Front page:
<img width="1231" alt="Screen Shot 2020-05-02 at 2 36 39 AM" src="https://user-images.githubusercontent.com/11865/80831630-c11c0280-8c1d-11ea-81d8-8bf86f146a23.png">

**Comment by opoudjis** [comment]
Following standard practice, this is `:edition:`.
