### ISSUE TITLE
Add URL

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-m3aawg#41]
<img width="817" alt="Screen Shot 2020-05-02 at 2 37 05 AM" src="https://user-images.githubusercontent.com/11865/80831660-d002b500-8c1d-11ea-817d-9a9f519c36c7.png">

A number of documents apparently have a specific URL that refers to it.

**Comment by opoudjis** [comment]
Will associate it with the `:uri:` document attribute.
