### ISSUE TITLE
Word: M3AAWG logo missing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-m3aawg#43]
<img width="1041" alt="Screen Shot 2020-05-14 at 2 15 49 PM" src="https://user-images.githubusercontent.com/11865/81899437-699e6f00-95ed-11ea-8b4e-e595b5e90f50.png">

**Comment by opoudjis** [comment]
Cannot replicate: see attached.


[cc-18003.doc.zip](https://github.com/metanorma/metanorma-m3aawg/files/5150416/cc-18003.doc.zip)
