### ISSUE TITLE
`term:[]` not working in m3aawg flavor?

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-m3aawg#67]
I'm trying to cross-reference terms by using `term:[]` and it seems not to be working in this flavor. (Or am I missing something?)
For example:

````
[[terms]]
== Terms, definitions and abbreviations

=== Terms and definitions

[[calendar-spam]]
==== calendar spam

calendar events and meeting invitations containing term:[spam] delivered
through _calendar systems_ (<<term-calendar-system>>)

[[term-spam]]
==== spam

unsolicited or unwanted information
````

results in

![Capture](https://user-images.githubusercontent.com/33627611/99586728-7c3f9980-29be-11eb-960a-6b60cdf35af9.PNG)

**Comment by opoudjis** [comment]
Though the macro is documented as generic Metanorma, it has only been implemented in the ISO flavour: https://github.com/metanorma/metanorma-iso/issues/255

Do we need to migrate it to generic Metanorma functionality? If not, then metanorma.com needs to be updated to treat this as ISO-only functionality

**Comment by ronaldtse** [comment]
@opoudjis yes please, we should generalize this functionality for all flavors. Let's ticket this. Thanks.
