### ISSUE TITLE
Large gap between section number and section title

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-m3aawg#70]
The horizontal space between number and title is too long in PDF output.

PDF:
![Capture1](https://user-images.githubusercontent.com/33627611/102569526-02cdc080-40bc-11eb-809e-72c46f126e36.PNG)
![Capture2](https://user-images.githubusercontent.com/33627611/102569530-04978400-40bc-11eb-9a85-fd68995fa620.PNG)

DOC:

![Capture3](https://user-images.githubusercontent.com/33627611/102569805-8a1b3400-40bc-11eb-8c68-bcff17b6b1f1.PNG)

Thanks!

**Comment by Intelligent2013** [comment]
Fixed.
![изображение](https://user-images.githubusercontent.com/5559926/102641822-c6f33380-416d-11eb-9449-78e2914b59b8.png)

**Comment by manuel489** [comment]
Thanks @Intelligent2013. Closing.
